name: Rust CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --workspace --all-targets --verbose
      - name: Run CLI
        run: cargo run -p cli
      - name: Run Example
        run: cargo run -p simple_app
